{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "rhaiis.routeName" . }}
  namespace: {{ include "rhaiis.namespace" . }}
  labels:
    {{- include "rhaiis.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "rhaiis.serviceName" . }}
    weight: 100
  {{- if .Values.route.tls }}
  tls:
    {{- toYaml .Values.route.tls | nindent 4 }}
  {{- end }}
  {{- if .Values.route.wildcardPolicy }}
  wildcardPolicy: {{ .Values.route.wildcardPolicy }}
  {{- end }}
{{- end }}
