apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rhaiis-cache
  namespace: rhaiis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: gp3-csi
