apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rhaiis-dev

resources:
- ../app

namePrefix: dev-

# Development-specific patches

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/instance: dev
    environment: development
patches:
- path: deployment-patch.yaml
